steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="env-secrets" > .env
        gcloud secrets versions access latest --secret="gcp-credentials" > key/credentials.json
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
options:
  logging: CLOUD_LOGGING_ONLY
